import type { ContentItem } from "@/types/literary";

export const literaryData: ContentItem[] = [
  // Found/Made Reflections
  {
    id: "1",
    content: "Hurt people, hurt people.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "2",
    content: "Let whoever, think whatever.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "3",
    content: "See everything, say nothing.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "4",
    content: "We mature from damage, not age.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "5",
    content: "Silent treatment goes both ways.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "6",
    content: "It's better to wait than to find.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "7",
    content: "You can't miss what was never yours.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "8",
    content: "Rain remembers what the sun forgets.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "9",
    content: "Beauty isn't found, it is recognized.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "10",
    content: "Slow motion is better than no motion.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "11",
    content: "Show no love. Love will get you killed.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "12",
    content: "Museum of failure or gallery of trying?",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "13",
    content: "You can't be brave if you're not afraid.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "14",
    content: "He lives the poetry that he cannot write.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "15",
    content: "Hurting them back will not heal your pain.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "16",
    content: "What is to give light must endure burning.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "17",
    content: "What if time is love unfolding in disguise?",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "18",
    content: "Nothing kills you faster than your own mind.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "19",
    content: "We belong to God and to Him we shall return.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "20",
    content: "You left so soon, I wasn't done loving you yet.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "21",
    content: "Beautiful souls are shaped by ugly experiences.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "22",
    content: "As long as you have yourself, you have someone.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "23",
    content: "For you are dust and to the dust You shall return.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "24",
    content: "You will always be the biggest threat to yourself.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "25",
    content: "Do not get attached to anything you found on Earth.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "26",
    content: "One's direction is more important than their speed.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "27",
    content: "Falling in love should never be part of one's plan.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "28",
    content: "Just as to bleed is to be alive, to love is to hurt.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "29",
    content: "You were the rain I danced in, unaware I was drowning.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "30",
    content: "How do you forget the one you cried in prayers to have?",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "31",
    content: "The storms in my head ruin the garden that my soul holds.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "32",
    content: "God will never let what you lost be the best you ever had.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "33",
    content: "Between life and death, lies an unexplainably calm silence.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "34",
    content: "I wish I wasn't slowly forgetting the way your voice sounds.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "35",
    content: "Who am I to judge another when my own soul is full of scars.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "36",
    content: "May the calm within you win over the chaos that surrounds you.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "37",
    content: "There is a crack in everything, that is how the light gets in.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "38",
    content: "Your name still tastes sweet, but I've lost the hunger for it.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "39",
    content: "We are not real until we ache for something that never existed.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "40",
    content: "In reality, I never got better. I only got better at masking it.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "41",
    content: "You can't heal if you keep holding what burns right through you.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "42",
    content: "Hearts can be wild creatures. Maybe that's why our ribs are cages.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "43",
    content: "Life and love isn't about what you gain, it's about what you give.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "44",
    content: "Close the window that hurts you, no matter how beautiful the view.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "45",
    content: "But how do you run away from the things that are inside your head?",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "46",
    content: "There's grief, and then the grief of a life you didn't get to live.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "47",
    content: "Be gentle with yourself, even growing feels like breaking at first.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "48",
    content: "If I ever saw a flaw of yours, I'd say my eyes are the flawed ones.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "49",
    content: "If you fixed all of your mistakes, would you really be you anymore?",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "50",
    content: "A person born in a burning house believes that the world is on fire.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "51",
    content: "A fool prays for an easier road, a wise man prays for stronger legs.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "52",
    content: "Peace is found not in perfection, but in the acceptance of imperfection.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "53",
    content: "A child who has spent his life in darkness will find no solace in light.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "54",
    content: "I wrote so much about you, my pen wonders what your existence truly holds.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "55",
    content: "It only hurts more knowing all the things you do is never targeted for me.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "56",
    content: "Peace isn't about control, it's about surrendering to what you can't change.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "57",
    content: "Even a correct decision transforms to a wrong one when it's applied too late.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "58",
    content: "Always pity the overthinkers, for they are cursed with their own imagination.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "59",
    content: "Maybe the happy ending is you continuing to be the soft loving person you are.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "60",
    content: "In order to love who you are, you cannot hate the experiences that shaped you.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "61",
    content: "The path doesn't appear before the walk, it appears because of it. Keep moving.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "62",
    content: "How silly of me to forget how far I've come just because I still have far to go.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "63",
    content: "If you are an ocean, be an ocean. Don't be a pond just because people can't swim.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "64",
    content: "You are so invested in how you are perceived, that you cannot fully enjoy living.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "65",
    content: "Every time we translate our chaos into calm, we lost a little more of who we were.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "66",
    content: "Somewhere beyond right and wrong, there is a garden, I will meet you there.",
    author: "Rumi",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "67",
    content: "There comes a time when nothing is meaningful except surrendering to love.",
    author: "Rumi",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "68",
    content: "I was a candle, you were the night. I burned for you, while you waited for the sun.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "69",
    content: "They say rain heals, but how can it heal a wound that's never been allowed to bleed?",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "70",
    content: "For those who love with heart and soul, there is no such thing as separation",
    author: "Rumi",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "71",
    content: "And I just wanna find myself in the middle of you",
    author: "Ax And The Hachetmen",
    source: "Hotel Room",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "72",
    content: "To be liked by others is a fleeting thing, to understand oneself is the greater task.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "73",
    content: "Let them call you difficult, the ocean never apologised for its depth. Why should you?",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "74",
    content: "Time is a moving object and it will not pay attention to any fragile heart in existence.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "75",
    content: "The darker the night the brighter the stars, so the deeper the grief the closer is God.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "76",
    content: "I hope you never stop visiting me in my dreams because now that's all I have left of you.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "77",
    content: "Don’t talk to them about loss, where were they when I was at my lowest, completely alone?",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "78",
    content: "To even picture one's dream coming true, one's ambition must be as boundless as the ocean.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "79",
    content: "Don't stress over things you can't control, you'll end up exhausted and lose sense of time.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "80",
    content: "People pretend you’re a bad person so they don’t feel guilty about the things they did to you.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "81",
    content: "When a clown moves into a palace, he doesn't become a king. The palace itself becomes a circus.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "82",
    content: "And soon, there will come a time where my eyes shall recognise you, but my heart no longer will.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "83",
    content: "The magic in our childhood wasn't because of being a child, it was because we lived in the present.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "84",
    content: "How could I be mad at the stove for burning my hand when I'm the one who reached out and touched it.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "85",
    content: "How fragile we are that the things keeping us alive can kill us too-water, heat, a conscious, love.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "86",
    content: "You are so ingrained in my skin that anyone who tries to know me will have to know your name first.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "87",
    content: "Having God in your boat doesn't mean you won't face any storms, it means no storm can sink your boat.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "88",
    content: "When you planted flowers in the graveyard of my heart, I thought you would be there to water them too.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "89",
    content: "The worst part about missing you was that I didn't know if I was allowed to-you were never really mine.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "90",
    content: "’Tis better to face an enemy who hates you openly than a friend who hides it and speaks behind your back.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "91",
    content: "They say poetry is beautiful but pain was never meant to be beautiful and blood was never meant to be ink.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "92",
    content: "You walked in, and every clock how to tick. I've seen beauty before, but never something that paused time.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "93",
    content: "Identity isn’t what stays. It’s what keeps returning despite the many attempts of others bringing it down.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "94",
    content: "Death is not the greatest loss in life, The greatest loss is what dies inside us while we are still alive.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "95",
    content: "And as the final act of my love for you, I'll let go, even though every atom that forms me wants to hold on.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "96",
    content: "After you, I won't seek love again, because I know if I do I'll be searching pieces of you in everyone I meet.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "97",
    content: "If a flower bloomed in the wrong season, would you call it a failure or a miracle?",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "98",
    content: "Be kind to your own timing.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "99",
    content: "If the rain that touches your skin traveled miles to find you, then so will everything that's written in your name.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "100",
    content: "I was naive and hopeful and lost, now I'm aware and trapped in my thoughts.",
    author: "The Neighbourhood",
    source: "R.I.P. 2 My Youth",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "101",
    content: "With just one glimpse of her unmatched beauty, it shattered; whatever inside me had only pretended to heal with time.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "102",
    content: "The land everybody is being negligent towards as of today, will become the land that holds control of everything one day.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "103",
    content: "Love death as much as you love life, for only the worst and utmost disgusting characters should fear the afterlife itself.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "104",
    content: "'The rearview mirror is meant for glancing, not staring'- So use it when you need to, but don't let your eyes reside in it.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "105",
    content: "Whoever abandoned you in the middle of the ocean has no right to know what the sharks did to you or how you managed it to the shore.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "106",
    content: "Days will pass, and you'll abandon things you were addicted to, and leave someone, and cancel a dream, and finally, accept a reality.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "107",
    content: "They say fate turns countless times for two souls to meet once, and if you miss the moment, it slips away with all that life had to offer.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "108",
    content: "Be disciplined, loyal, dependable, and true to your word, as success isn't found in your job, It is found in the man you choose to become.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "109",
    content: "If all the poetry that includes our painful statements could bleed, the world would be stained with all the world that failed to escape from our mouths.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "110",
    content: "You only notice the holes in the roof when it starts to rain, so conceal the holes in the roof before you suffer from the water that silently invades your home.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },
  {
    id: "111",
    content: "Everything about me is black. Except for the centre of my heart where I've kept you. It glows blood red at all times, and sport green when it is in front of you.",
    author: "Anonymous",
    source: "",
    category: "found-made",
    type: "reflection",
  },

  // From Cinema
  {
    id: "112",
    content: "First it hurts, then it changes you.",
    author: "Tony Montana",
    source: "Scarface (1983)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "113",
    content: "They can't see what I see in you.",
    author: "Gaspard",
    source: "A Summer's Tale (1996)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "114",
    content: "We all make mistakes and we all pay a price.",
    author: "Dr. Gregory House",
    source: "House (2004-2011)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "115",
    content: "The world's just really fuckin' ugly, you know?",
    author: "Rue Bennett",
    source: "Euphoria (2019)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "116",
    content: "Oh, wow! I have no words to describe your beauty!",
    author: "Anonymous",
    source: "Taj Mahal (1989)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "117",
    content: "To feel. To trust the feeling. I long for that.",
    author: "Dr. Jenny Isaksson",
    source: "Face To Face (1976)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "118",
    content: "Why do fireflies have to die so soon?",
    author: "Setsuko",
    source: "Grave of the Fireflies (1988)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "119",
    content: "Nature is a mirror in which we can study ourselves.",
    author: "Hossain Sabzian",
    source: "Close-Up (1990)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "120",
    content: "Nobody feels sorry for you and nobody ever will.",
    author: "Wilson Fisk",
    source: "Daredevil (2015-2018)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "121",
    content: "And the more people I cut out, the quieter my life got.",
    author: "Carmen 'Carmy' Berzatto",
    source: "The Bear (2022)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "122",
    content: "When you leave something behind, you gain something too.",
    author: "Nora",
    source: "Past Lives (2023)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "123",
    content: "I don't know much, but the innocent don't control this world.",
    author: "Carmen",
    source: "Carmen (1983)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "124",
    content: "Not all the people who are nice to you has good intentions.",
    author: "Coraline Jones",
    source: "Coraline (2009)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "125",
    content: "I'm journeying into darkness anyhow, so I really don't care.",
    author: "Lemmy Caution",
    source: "Alphaville (1965)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "126",
    content: "What cannot be forgotten... reappears in dreams.",
    author: "Anonymous",
    source: "Critique of Separation (1961)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "127",
    content: "I will return, find you, love you, marry you. And live without shame.",
    author: "Robbie Turner",
    source: "Atonement (2007)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "128",
    content: "Seems like there's something missing in me that the rest of the world has.",
    author: "Pearl",
    source: "Pearl (2022)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "129",
    content: "It's only after we've lost everything that we're free to do anything.",
    author: "Tyler Durden",
    source: "Fight Club (1999)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "130",
    content: "We have so much to say, and we shall never say it.",
    author: "Paul Bäumer",
    source: "All Quiet On The Western Front (2022)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "131",
    content: "You have to decide what kind of man you want to grow up to be, Clark.",
    author: "Jonathan Kent",
    source: "Man of Steel (2013)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "132",
    content: "You don't have to know someone to feel sad for them. It's empathy.",
    author: "Johnny",
    source: "Frankie and Johnny (1991)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "133",
    content: "There are still a lot of things I don't understand. That's how life goes.",
    author: "Hirayama",
    source: "Perfect Days (2023)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "134",
    content: "I've been doin' a lot of thinkin', and the thing is, I love you.",
    author: "Harry Burns",
    source: "When Harry Met Sally… (1989)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "135",
    content: "People's superficial aspects don't interest me, the deeper ones do.",
    author: "Marion",
    source: "Pauline at the Beach (1983)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "136",
    content: "You don't always have to be who they want you to be, you know?",
    author: "Patrick Verona",
    source: "10 Things I Hate About You (1999)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "137",
    content: "There are monsters who act like people, and people who act like monsters.",
    author: "Mr. Okuyama",
    source: "The Face of Another (1966)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "138",
    content: "You never wanted to be anybody's girlfriend and now you're somebody's wife.",
    author: "Tom Hansen",
    source: "500 Days of Summer (2009)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "139",
    content: "He's your first love. I intend to be your last.. however long it takes.",
    author: "Klaus Mikaelson",
    source: "The Vampire Diaries (2009-2017)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "140",
    content: "I just woke up one day and knew. Knew what? What I was never sure of with you.",
    author: "Summer Finn",
    source: "500 Days of Summer (2009)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "141",
    content: "Trust me, Peter, when you try to fix people, there are always consequences.",
    author: "Dr. Strange",
    source: "Spider-man No Way Home (2021)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "142",
    content: "But it's no good if there isn't somebody you can turn to and say, \"Nice view, huh?\"",
    author: "Jeff Bailey",
    source: "Out of the Past (1947)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "143",
    content: "No matter how much you change... you still have to pay the price for the things you've done.",
    author: "Doug MacRay",
    source: "The Town (2010)",
    category: "cinema",
    type: "quote",
  },
  {
    id: "144",
    content: "Listen kid, nobody cares. Worry about yourself, your family and the people who are important to you.",
    author: "Sonny LoSpecchio",
    source: "A Bronx Tale (1993)",
    category: "cinema",
    type: "quote",
  },

  // Literary Masters
  {
    id: "145",
    content: "Deep rivers run quiet.",
    author: "Haruki Murakami",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "146",
    content: "She needed someone already grown.",
    author: "Franz Kafka",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "147",
    content: "He who is brave is free.",
    author: "Lucius Annaeus Seneca",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "148",
    content: "I wanted her to grow with me.",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "149",
    content: "Leave me to my own absurdity.",
    author: "Sophocles",
    source: "Antigone",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "150",
    content: "He who dares not offend cannot be honest.",
    author: "Thomas Paine",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "151",
    content: "come back, come back to me",
    author: "Ian McEwan",
    source: "Atonement",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "152",
    content: "Dearest, accept me as I am.",
    author: "Franz Kafka",
    source: "to Felice Bauer",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "153",
    content: "No two people can know the sea the same way.",
    author: "Mahmoud Darwish",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "154",
    content: "I am too young and I've loved you too much.",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "155",
    content: "I did violence to my own heart",
    author: "Edgar Allan Poe",
    source: "to S.H Whitman",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "156",
    content: "I ran from love because I knew it would destroy me.",
    author: "Franz Kafka",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "157",
    content: "I crave a love so deep, the ocean would be jealous.",
    author: "Pablo Neruda",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "158",
    content: "As for myself, I had a lot to say. But I was silent.",
    author: "Albert Camus",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "159",
    content: "We do not see things as they are, we see them as we are.",
    author: "Anais Nin",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "160",
    content: "Your hand is cold, mine burns like fire. How blind you are, Nastenka!",
    author: "Fyodor Dostoevsky",
    source: "White Nights",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "161",
    content: "Forgive me, memory is a rope around the neck.",
    author: "Clementine von Radics",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "162",
    content: "And what I really intended to say in the end remains unsaid.",
    author: "Franz Kafka",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "163",
    content: "Darling, the moon is still the moon in all of its phases.",
    author: "Isra Al-Thibeh",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "164",
    content: "I am the sea and nobody owns me.",
    author: "Pippi Longstocking",
    source: "Dir. Clive A. Smith",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "165",
    content: "Of all the ways to lose a person, Death is the kindest.",
    author: "Ralph Waldo Emerson",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "166",
    content: "Time was a wave, almost cruel in its relentlessness",
    author: "Han Kang",
    source: "The Vegetarian",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "167",
    content: "I haven't yet tasted everything that can keep me alive.",
    author: "Albert Camus",
    source: "Caligula",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "168",
    content: "If it is humanly possible, consider it to be within your reach.",
    author: "Marcus Aurelius",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "169",
    content: "It's been a long time since I've been me.",
    author: "Fernando Pessoa",
    source: "The Book of Disquiet",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "170",
    content: "If pain can purify the heart, mine will be pure.",
    author: "Mary Shelley",
    source: "Mathilda",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "171",
    content: "My brain hums with scraps of poetry and madness.",
    author: "Virginia Woolf",
    source: "Selected Letters",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "172",
    content: "I ran into love because I needed it to destroy who I used to be.",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "173",
    content: "I hid my pain even from myself; I revealed my pain only to myself.",
    author: "Agha Shahid Ali",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "174",
    content: "Everything you say should be true, but not everything true should be said.",
    author: "Voltaire",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "175",
    content: "All I ever wanted was to know what to do.",
    author: "Dave Eggers",
    source: "You Shall Know Our Velocity!",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "176",
    content: "To live is the rarest thing in the world. Most people exist, that is all.",
    author: "Oscar Wilde",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "177",
    content: "But the heart has its own memory and I have forgotten nothing.",
    author: "Albert Camus",
    source: "The Fall",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "178",
    content: "There are times when I am convinced I am unfit for any human relationship.",
    author: "Franz Kafka",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "179",
    content: "The greatest thing you'll ever learn is just to love and be loved in return.",
    author: "Eden Ahbez",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "180",
    content: "How about if I sleep a little bit longer and forget about all this nonsense.",
    author: "Franz Kafka",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "181",
    content: "The world is a tragedy to those who feel, but a comedy to those who think.",
    author: "Horace Walpole",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "182",
    content: "Out of love for you, I have forgiven the world.",
    author: "Alexandre Dumas",
    source: "The Count of Monte Cristo",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "183",
    content: "People who bite the hand that feeds them usually lick the boot that kicks them.",
    author: "Eric Hoffer",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "184",
    content: "A leaf does not cease to be a leaf merely because a storm tore it from the tree.",
    author: "Paulo Coelho",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "185",
    content: "Your worst sin is that you have destroyed and betrayed yourself for nothing.",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "186",
    content: "I look forward and see myself look back.",
    author: "Erica Jong",
    source: "Becoming Light: Poems New & Selected",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "187",
    content: "But to fall in love does not mean to love. One can fall in love and still hate.",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "188",
    content: "I want to talk about everything with at least one person as I would with myself.",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "189",
    content: "If you feel pain, you're alive. If you feel other people's pain, you're a human being.",
    author: "Leo Tolstoy",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "190",
    content: "There must be something strangely sacred in salt. It is in our tears and in the sea.",
    author: "Khalil Gibran",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "191",
    content: "Maybe all one can do is hope to end with the right regrets.",
    author: "Arthur Miller",
    source: "The Ride Down Mt. Morgan",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "192",
    content: "Pain and suffering are always inevitable for a large intelligence and a deep heart.",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "193",
    content: "Dead people receive more flowers than the living because regret is stronger than gratitude.",
    author: "Anne Frank",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "194",
    content: "I'm not upset that you lied to me, I'm upset that from now on I can't believe you.",
    author: "Friedrich Nietzsche",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "195",
    content: "It is better to be unhappy and know the worst, than to be happy in a fool's paradise.",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "196",
    content: "I am both worse and better than you thought.",
    author: "Sylvia Plath",
    source: "The Unabridged Journals of Sylvia Plath",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "197",
    content: "Despite this feeling of time standing still, I had in fact changed.",
    author: "Margaret Atwood",
    source: "The Testaments",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "198",
    content: "And in the silence I suddenly understood the many ways a person can die but still be alive.",
    author: "Carmen Rodrigues",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "199",
    content: "A person is, among all else, a material thing, easily torn and not easily mended.",
    author: "Ian McEwan",
    source: "Atonement",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "200",
    content: "Everything you love is very likely to be lost, but in the end, love will return in a different way.",
    author: "Franz Kafka",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "201",
    content: "If the book we read does not wake us, as with a fist hammering on our skull, why then do we read it?",
    author: "Franz Kafka",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "202",
    content: "And that's the thing about people who mean everything they say. They think everyone else does too.",
    author: "Khaled Hosseini",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "203",
    content: "Sometimes people don't want to hear the truth, because they don't want their illusions destroyed.",
    author: "Friedrich Nietzsche",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "204",
    content: "You will never know who I am in reality because the depth of existence exceeds the limit of understanding.",
    author: "Taha Zainab",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "205",
    content: "I don't feel particularly proud of myself. But when I walk alone in the woods or lie in the meadows, all is well.",
    author: "Franz Kafka",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "206",
    content: "Most of our childhood is stored not in photos, but in certain biscuits, lights of day, smells, textures of carpet.",
    author: "Alain de Botton",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "207",
    content: "I am tired. These people make me feel I have a hole in the middle of me.",
    author: "D.H. Lawrence",
    source: "The Complete Works; The Plumbed Serpent",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "208",
    content: "People do not see you, They invent you and accuse you.",
    author: "Helene Cixous",
    source: 'The Selected Plays of Helene Cixous; "The Perjured City,"',
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "209",
    content: "People label themselves with all sorts of adjectives. I can only pronounce myself as \"nauseatingly miserable beyond repair\".",
    author: "Franz Kafka",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "210",
    content: "Sadness is caused by intelligence, the more you understand certain things, the more you wish you didn't understand them.",
    author: "Charles Bukowski",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "211",
    content: "Everyone seems to have a clear idea of how other people should lead their lives, but none about his or he own.",
    author: "Paulo Coelho",
    source: "The Alchemist",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "212",
    content: "I wanted to cry out, to ask her not to go. But what right I had to hold her back when her happiness lay in another's arms?",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "213",
    content: "When it's gone, you'll know what a gift love was. You'll suffer like this. So go back and fight to keep it.",
    author: "Ian McEwan",
    source: "Enduring Love",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "214",
    content: "I've never had a moment's doubt. I love you. I believe in you completely. You are my dearest one. My reason for life.",
    author: "Ian McEwan",
    source: "Atonement",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "215",
    content: "You cannot make everyone think and feel as deeply as you do. this is your tragedy, because you understand them but they don't understand you.",
    author: "Daniel Saint",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "216",
    content: "Talk nonsense, but talk your own nonsense, and I'll kiss you for it. To go wrong in one's own way is better to go right in someone else's.",
    author: "Fyodor Dostoevsky",
    source: "",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "217",
    content: "I am a fool with a heart but no brains, and you are a fool with brains but no heart; and we're both unhappy, and we both suffer.",
    author: "Fyodor Dostoevsky",
    source: "The Idiot",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "218",
    content: "My God, my God, whose performance am I watching? How many people am I? Who am I? What is this space between myself and myself?",
    author: "Fernando Pessoa",
    source: "The Book of Disquiet",
    category: "literary-masters",
    type: "quote",
  },
  {
    id: "219",
    content: "I wouldn't let you know, but even if all the rains in the world drown me, I would still choose to refuse a sunny day if it was you, who offered it.",
    author: "Anonymous",
    source: "Strings, Pg. 146",
    category: "literary-masters",
    type: "quote",
  },

  // Spiritual Reflections
  {
    id: "220",
    content: "Every soul shall taste death.",
    author: "Quran",
    source: "Surah Al-Anbiya, verse 35",
    category: "spiritual",
    type: "quote",
  },
  {
    id: "221",
    content: "Oh my Lord! I am face to face the favor you will shower upon me.",
    author: "Quran",
    source: "Surah Kas'as, verse 24",
    category: "spiritual",
    type: "quote",
  },
  {
    id: "222",
    content: "You liars! If Allah were to throw the stones through my window, he would not miss.",
    author: "Uthmaan RA",
    source: "",
    category: "spiritual",
    type: "quote",
  },

  // Original Poetry
  {
    id: "223",
    content: `"Lost"\n\nThey say you can't lose what was never yours,\nbut love, for a moment, opened its doors.\nShe was mine in a glance, in a breath, in a flame,\nBut now only the silence remembers her name.`,
    author: "Fatin",
    source: "",
    category: "original-poetry",
    type: "poem",
  },
  {
    id: "224",
    content: `"Something"\n\nwe were almost something.\nnot quite lovers, not just friends—just two people standing at the edge of a maybe.\nthere were glances that lingered a second too long.\nsilences that said more than our words ever dared.\nyou held my gaze like it meant something.\ni held my breath like it could change everything.\nbut we never stepped forward.\nmaybe out of fear.\nmaybe out of timing.\nmaybe because we both knew,\nalmost is safer than heartbreak.\nstill, sometimes i wonder what we could’ve been, if “almost” had dared to become more.`,
    author: "Fatin",
    source: "",
    category: "original-poetry",
    type: "poem",
  },
  {
    id: "225",
    content: `"Almost"\n\nWe were almost, but not quite\na spark lost in the endless night.\nNot lovers, not quite friends,\njust me hoping the story bends.\nYour words were light, a gentle breeze,\nbut never meant to bring me ease.\nYou held my gaze, or so I'd thought-\nwhile I caught feelings you never sought.\nI stayed awake on silent screens,\nchasing shadows, chasing dreams.\nWe never touched, not hand or heart,\nyet still it tore me all apart.\nMaybe you never saw me there,\nmaybe you simply didn’t care.\nAlmost hurt me, but I stayed—\nclinging to what you never gave.\nNow I watch you drift away,\na ghost I loved, who couldn’t stay.\nAnd wonder still, as nights grow long,\nwhat’s left of me in your silent song?`,
    author: "Fatin",
    source: "",
    category: "original-poetry",
    type: "poem",
  },
  {
    id: "226",
    content: `"Coffee"\n\nthe coffee didn’t fix me,\nbut it stayed warm\nlong enough\nfor me to breathe again.\nno deep thoughts this time,\njust the hum of the machine\nand the way silence\nsometimes says more\nthan advice ever could.\ni sat there,\nhalf-sinking into my own weight,\nwatching steam curl like\na tired exhale —\ngentle,\nbut still here.\ni didn’t cry.\ndidn’t smile, either.\ni just existed,\nand that was enough\nfor now.\nsome days,\nhealing doesn’t look like a breakthrough.\nit looks like not pouring the cup down the sink.\nit looks like showing up,\neven if you’re quiet about it.\nand the coffee?\nstill warm.\nso maybe i’m not too far gone.`,
    author: "Fatin",
    source: "",
    category: "original-poetry",
    type: "poem",
  },
  {
    id: "227",
    content: `"Almost Known"\n\nBeneath the weight of rolling years,\nI stood two steps behind her fears.\nA stranger caught in a glowing screen,\nwhere shadows melted into night’s sheen.\nShe came from places I’d not known,\na world beyond my sheltered zone.\nHer words at first, a distant song,\nyet slowly, they would pull me strong.\nShe held her truth, steady, kind,\nher place was right, though worlds aligned\nin different beats within one heart—\na quiet space where dreams might start.\nAt first unsure, my feelings grew,\na quiet hope that stayed true.\nShe met me kind, but kept her space—\na friendzone’s gentle, warm embrace.\nToo shy, too young, not quite her match,\na flame I longed for but couldn’t catch.\nYet in her voice and memories kept,\na love asleep inside me slept.\nThough almost love can bring its pain,\nit leaves a melody to gain—\na fragile hope that time may show\nwhat almost could become, and grow.\nI wait where silence gently falls,\nbetween the space of distant walls.\nNo rush to come, no need to say—\nI’m here, if you should find your way.`,
    author: "Fatin",
    source: "",
    category: "original-poetry",
    type: "poem",
  },
  {
    id: "228",
    content: `"Unspoken"\n\nthey say some girls don’t need to speak\nto hold their ground, to stand unique.\nit’s in their presence, how they move\na quiet power, hard to prove.\nhe wasn’t fully grown, still learning how to be alone.\nlife moved fast;\nhe barely kept\nthe pace of feelings he had never met.\nit started in an online space—\njust classmates, games, a slower pace.\ntheir school was boys alone, no mix,\nso encountering her there—it didn’t click.\nshe was older, a little loud, a little keen.\nat first, he found her hard to read,\nbut maybe he just couldn’t lead.\nthen slowly, something shifted pace.\nshe lingered—a voice, a glimpse, a face.\nno big moment, no clear start,\njust silence creeping through the heart.\nthey weren’t close—just names online.\nbut still, she managed to live beneath his spine.\n'a crush', he thought. it would decay.\nbut no—it stayed.\nit found its way.\nthen someone caught the way he fell.\nthe rumor spread. the silence shook.\nwithin an hour, all had heard.\nhe smiled. he lied. he said no word.\nin September, he let it show—\na message sent, a quiet “no.”\nshe let him down with something kind.\nit didn’t break him—not at the time.\nhe fell too fast, confessed too soon,\nmistook a spark to mean full moon.\nwith heart untrained, he leapt ahead—\nand faced the quiet hurt instead.\nbut later, it began to sting,\na hollow kind of echoing.\nshe wasn’t wrong;\nshe owed him none\nof what he hoped could be begun.\nlife unraveled bit by bit—\nat home, at school, inside, he'd quit.\nstill, sometimes, she would message back.\nno promise made, no deeper track.\nhe saved her words, her voice, her face—\nnot out of need, just in case\nhe’d want to feel what once had been\na moment that he had wandered in.\nthey never met.\nit stayed like that.\nsometimes he wonders if that’s flat—\na dream untouched that feels safe, unknown,\nless fragile than what's fully grown.\n"it’s odd," he said with a distant stare,\nstill lost in a face he’d never met there.\na photo held what time made blur—\nhow did he fall in love with her?\nhe tried to date, he tried to heal.\nbut nothing really felt as real.\nand somehow, he was back again—\nher voice familiar as a friend.\nthis time, talks grew late and soft.\nbut still, the ground was never loft.\none wrong word, a shift, a pause—\nand suddenly, the silence was because..\nshe blocked him from the space she hid,\nbut left one place where he still slid.\nshe asked if he still liked her. yes.\nbut, not like then. or maybe, even more.\nhe cared for who they never were,\nand maybe still, he cares for her.\nshe taught him things that he didn’t know:\nthat love’s not always built to grow,\nthat feelings young aren’t always small,\nand that silence doesn’t mean no fall.\nsome people come and shape the way\nyou look at love, then walk away.\nnot villains, heroes, or "the one"—\njust someone who, by chance, begun\na chapter you will always keep—\nnot loud or deep—\nbut quietly, when you're half asleep.`,
    author: "Fatin",
    source: "",
    category: "original-poetry",
    type: "poem",
  },
];
